//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieListing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Actor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Actor()
        {
            this.Movies = new HashSet<Movy>();
        }
    
        public int ActorID { get; set; }
        [Required(ErrorMessage = "Actor Name is required.")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "Name should not be minimum 2 characters and maximum of 100.")]
        [Display(Name = "Actor Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Specify Male, Female or Other")]
        public string Sex { get; set; }
        [Required(ErrorMessage = "Please Specify Datetime in YYYY-MM-DD Format")]
        public System.DateTime DOB { get; set; }
        [Required(ErrorMessage = "Actor Biography is needed")]
        public string Bio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movy> Movies { get; set; }
    }
}
