//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieListing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Movy
    {
        public int MovieID { get; set; }
        public string Name { get; set; }
        [Display(Name = "Year of Release")]
        public System.DateTime YearOfRelease { get; set; }
        public string Plot { get; set; }
        public string Poster { get; set; }
        public Nullable<int> ActorID { get; set; }
        public Nullable<int> ProducerID { get; set; }

        public HttpPostedFileBase file { get; set; }

        public virtual Actor Actor { get; set; }
        public virtual Producer Producer { get; set; }
    }
}
